baseURL = "https://arshsiddiqui.pages.dev/"
languageCode = "en-us"
title = "Arsh Siddiqui"
theme = 'hugo-book'

[languages]
	[languages.en]
		languageName = 'English'
		contentDir = 'content.en'
		weight = 1
		[languages.en.menus]
			[[languages.en.menus.main]]
				name = 'Blog'
				pageRef = '/blog'
				weight = 10
	[languages.fr]
		languageName = 'French'
		contentDir = 'content.fr'
		weight = 2

[params]
	BookTheme = 'auto'
	BookDateFormat = 'Jan 2, 2006'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
